[book]
title = "Tyrion's blogs"
author = "Tyrion"
language = "en"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/ZZ7012/TyrionBlog"

[preprocessor.foo]
# Add any additional configurations